# Generated by Django 3.2.6 on 2024-03-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('lat_coord', models.DecimalField(blank=True, db_column='lat_coord', decimal_places=6, max_digits=10, null=True)),
                ('long_coord', models.DecimalField(blank=True, db_column='long_coord', decimal_places=6, max_digits=10, null=True)),
                ('soil_moisture', models.DecimalField(blank=True, db_column='soil_moisture', decimal_places=4, max_digits=10, null=True)),
                ('soil_temp', models.DecimalField(blank=True, db_column='soil_temp', decimal_places=4, max_digits=10, null=True)),
                ('atm_moisture', models.DecimalField(blank=True, db_column='atm_moisture', decimal_places=4, max_digits=10, null=True)),
                ('atm_temp', models.DecimalField(blank=True, db_column='atm_temp', decimal_places=4, max_digits=10, null=True)),
                ('light_intensity', models.DecimalField(blank=True, db_column='light_intensity', decimal_places=4, max_digits=10, null=True)),
                ('nitro_cont', models.DecimalField(blank=True, db_column='nitro_cont', decimal_places=4, max_digits=10, null=True)),
                ('phos_cont', models.DecimalField(blank=True, db_column='phos_cont', decimal_places=4, max_digits=10, null=True)),
                ('soil_ph', models.DecimalField(blank=True, db_column='soil_ph', decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': True,
            },
        ),
    ]
